id: AC03FAFB4
title: 'Treasury of Supreme Blessings: A Guru Yoga'
type: translation
pechas:
- I870484EE
- I05C91D71
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:00.108445
  last_modified_at: 2023-01-04 12:01:00.108449
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I870484EE/F0A2: 5F77
  I05C91D71/0904: 5F77
